PARSIMONY_PROBLEM: true
AMP: true
ENV:
  ENVIRONMENT_TYPE: ONE_STEP_BINARY_TREE
  SEQUENCE_TYPE: DNA_WITH_GAP
  REWARD:
    RESHAPE_METHOD: EXPONENTIAL
    C: 2300.0
    SCALE: 4.0
GFN:
  SCALES_SET:
    - 4.0
    - 2.0
    - 1.0
    - 0.5
    - 0.25
  SCALES_SAMPLING_SIGMA:
    0.5
  BACKWARD_MODELING: UNIFORM
  CONDITION_ON_SCALE: false
  LOSS_TYPE: 'TB'
  TRAINING_DATA_LOADER:
    BEST_STATE_BATCH_SIZE: 32
    BEST_TREES_BUFFER_SIZE: 100
    EPOCHS_NUM: 400
    FREQ_UPDATE_MODEL_WEIGHTS: 20
    GFN_BATCH_SIZE: 32
    MINI_BATCH_SPLITS: 2
    NUM_WORKERS: 16
    PERTURB_BUFFERED_TREE: false
    RANDOM_ACTION_PROB: 0.001
    RANDOM_BATCH_SIZE: 0
    STEPS_PER_EPOCH: 1000
    EPS_ANNEALING: true
    EPS_ANNEALING_DATA:
      END_EPS: 0.001
      T: 240
  MODEL:
    TRANSFORMER:
      DEPTH: 6
      USE_TREE_TYPE_EMBEDDING: false
      SEQ_EMB:
        INPUT_SIZE: 1890
        OUTPUT_SIZE: 128
        LAYERS: 0
      LOGITS_HEAD:
        ACT_FN: ELU
        CONCATENATE_SUMMARY_TOKEN: true
        INPUT_SIZE: 256
        HIDDEN_SIZE: 256
      FLOW_HEAD:
        ACT_FN: ELU
        INPUT_SIZE: 128
        HIDDEN_SIZE: 256
      SHARED_ENCODER: true
    Z_MLP:
      ACT_FN: ELU
      HIDDEN_SIZE: 128
      INPUT_SIZE: 128
      LAYERS: 1
      OUTPUT_SIZE: 1
    SCALE_MLP:
      ACT_FN: ELU
      HIDDEN_SIZE: 256
      INPUT_SIZE: 1
      LAYERS: 3
      OUTPUT_SIZE: 128
    Z_PARTITION_INIT: 5
    EVALUATION:
      BATCH_SIZE: 32
      NUM_WORKERS: 16
      BINS_NUM: 10
      EVALUATION_FREQ: 20
      MAX_DUPLICATE_MUTATIONS: 5
      MUTATIONS_TRAJS: 10000
      PROB_ESTIMATION_METHOD: IMPORTANCE_SAMPLING
      SAME_TREE_STRUCTURE: false
      STATES_GENERATION_METHOD: UNIFORM_BINS
      STATES_NUM: 100
      TRAJECTORIES_PER_STATES: 100


